<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>sbom-example-maven</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>33.6.0-jre</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <!-- Contains Log4Shell -->
            <version>2.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- CycloneDX -->
            <!-- Output can be found in target/bom.json (or.xml) -->
            <plugin>
                <groupId>org.cyclonedx</groupId>
                <artifactId>cyclonedx-maven-plugin</artifactId>
                <version>2.9.2</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>makeAggregateBom</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- SPDX -->
            <!-- Output can be found in target/site/....spdx.json -->
            <plugin>
                <groupId>org.spdx</groupId>
                <artifactId>spdx-maven-plugin</artifactId>
                <version>1.0.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <id>build-spdx</id>
                        <goals>
                            <goal>createSPDX</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- SWID -->
            <!-- Output can be found in classes/META-INF/SWIDTAG/... -->
            <plugin>
                <groupId>gov.nist.secauto.swid</groupId>
                <artifactId>swid-maven-plugin</artifactId>
                <version>0.6.1</version>
                <configuration>
                    <entities>
                        <entity>
                            <name>MusterName</name>
                            <regid>musterRegId</regid>
                            <roles>
                                <role>tagCreator</role>
                            </roles>
                        </entity>
                    </entities>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
